### ISSUE TITLE
[Feat] 建议新增云服务控制台配置域名

### ISSUE THREAD

**Issue by EmptyZeroRain** [wgpsec/cloudsword#2]
### 描述你希望增加的功能

很多基于公有云进行私有化部署的行业云，例如政务云等，基于阿里云盾私有化部署的，建议在云控制台上新增域名配置功能

### 补充信息 (Anything else?)

![image](https://github.com/user-attachments/assets/46c2389d-8b21-430b-93ed-934ef3af0825)

**Comment by teamssix** [comment]
不太理解您的问题，您指的是增加云鉴对私有云的支持吗？

**Comment by EmptyZeroRain** [comment]
云鉴对行业云的支持

**Comment by teamssix** [comment]
了解，感谢反馈，只是我没有相应的环境去测试，无法开发相关功能，如果有机会去测试这类环境的话，到确实可以考虑加入相关功能。
